version: '3'

services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    expose:
      - "33060"
    ports:
      - "33060:3306"
